version: '2'
services:
  client:
    image: "nikita/opencv:1.0"
    networks:
    - server_lab
    volumes:
    - .:/opt
    container_name: opencv_client
    command: /opt/do.sh
networks:
  server_lab:
    external: true
